services:
    
    bitbag.payu_plugin.command_provider.payu_payment:
        class: Sylius\Bundle\PaymentBundle\CommandProvider\ActionsCommandProvider
        arguments:
            - !tagged_locator
                tag: bitbag.payu_plugin.command_provider.payu_payment
                index_by: 'action'
        tags:
            - name: sylius.payment_request.command_provider
              'gateway-factory': 'payu_payment'

    bitbag.payu_plugin.command_provider.payu_payment.capture:
        class: BitBag\SyliusPayUPlugin\CommandProvider\CapturePaymentRequestCommandProvider
        tags:
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_CAPTURE
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_AUTHORIZE

    bitbag.payu_plugin.command_provider.payu_payment.status:
        class: BitBag\SyliusPayUPlugin\CommandProvider\StatusPaymentRequestCommandProvider
        tags:
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_STATUS
    
    bitbag.payu_plugin.command_provider.payu_payment.notify:
        class: BitBag\SyliusPayUPlugin\CommandProvider\NotifyPaymentRequestCommandProvider
        tags:
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_NOTIFY
    
    bitbag.payu_plugin.command_provider.payu_payment.cancel:
        class: BitBag\SyliusPayUPlugin\CommandProvider\CancelPaymentRequestCommandProvider
        tags:
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_CANCEL
    
    bitbag.payu_plugin.command_provider.payu_payment.refund:
        class: BitBag\SyliusPayUPlugin\CommandProvider\RefundPaymentRequestCommandProvider
        tags:
            - name: bitbag.payu_plugin.command_provider.payu_payment
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_REFUND
