services:
    
    bitbag.payu_plugin.processor.payment_transition.checkout:
        class: BitBag\SyliusPayUPlugin\Processor\Checkout\CheckoutSessionTransitionProcessor
        arguments:
            - '@sylius_abstraction.state_machine'
    
