services:
    
    bitbag.payu_plugin.event_listener.workflow.payment_complete_state.cancel:
        class: BitBag\SyliusPayUPlugin\EventListener\Workflow\PaymentCompletedStateListener
        arguments:
            - '@bitbag.payu_plugin.state_machine.cancel'
        tags:
            - name: kernel.event_listener
              event: workflow.sylius_payment.completed.cancel

    bitbag.payu_plugin.event_listener.workflow.payment_complete_state.refund:
        class: BitBag\SyliusPayUPlugin\EventListener\Workflow\PaymentCompletedStateListener
        arguments:
            - '@bitbag.payu_plugin.state_machine.refund'
        tags:
            - name: kernel.event_listener
              event: workflow.sylius_payment.completed.refund
    
    bitbag.payu_plugin.event_listener.workflow.payment_complete_state.complete_authorized:
        class: BitBag\SyliusPayUPlugin\EventListener\Workflow\PaymentCompletedStateListener
        arguments:
            - '@bitbag.payu_plugin.state_machine.capture_authorized'
        tags:
            - name: kernel.event_listener
              event: workflow.sylius_payment.completed.complete
